spring:
    application:
        name: sharphin
    datasource: 
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/sharphin
        username: sharphin
        password: fk5i9dtu
    sql:
        init:
            mode: always
            encoding: UTF-8
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 50MB

        
        